server {
    listen 80;
    listen [::]:80;
#    server_name tutavps.online;

    index index.php index.html;
    charset utf-8;

    root /opt/TutaTeam/public;

#    ssl_certificate /etc/nginx/ssl/fullchain.pem;
#    ssl_certificate_key /etc/nginx/ssl/privkey.key;

#    ssl_protocols TLSv1.2 TLSv1.3;
#    ssl_ciphers HIGH:!aNULL:!MD5;

#    ssl_session_timeout 1d;
#    ssl_session_cache shared:MozSSL:10m;
#    ssl_session_tickets    off;

#    ssl_stapling           on;
#    ssl_stapling_verify    on;
#    resolver               1.1.1.1 1.0.0.1 8.8.8.8 8.8.4.4 208.67.222.222 208.67.220.220 valid=60s;
#    resolver_timeout       2s;

    # Оборона
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;

    # Обработка PHP
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_read_timeout 1000;
        proxy_read_timeout 1000;
        error_page 504 /;
    }

    # Обработка Gzip
    gzip on;
    gzip_proxied any;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml app>    gzip_vary on;
    gzip_comp_level 6;

    # Маршрутизация Laravel
    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }

    # Игнорирование лишнего (Favicon и Robots)
        # Игнорирование лишнего (Favicon и Robots)
        location = /favicon.ico { access_log off; log_not_found off; }
        location = /robots.txt  { access_log off; log_not_found off; }

        # Защита скрытых файлов (набор символов, который мы разобрали)
        location ~ /\.(?!well-known).* {
            deny all;
        }
        # Маршрутизация с HTTP через HSTS
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    }

#    server {
#        listen 80;
#        server_name tutavps.online www.tutavps.online;
#        return 301 https://$host$request_uri;
#    }

#    server {
#        listen 443 ssl default_server reuseport;
#        listen [::]:443 ssl default_server reuseport;

#        server_name _;
#        ssl_reject_handshake on;
#    }
